# Generated by Django 3.2.3 on 2021-06-12 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Bendra kaina')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategorijos pavadinimas')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono numeris')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresas')),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Atvaizdas')),
                ('description', models.TextField(null=True, verbose_name='Aprašymas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Kaina')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Įstrižainė')),
                ('display_type', models.CharField(max_length=255, verbose_name='Ekrano tipas')),
                ('resolution', models.CharField(max_length=255, verbose_name='Ekrano raiška')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Akumuliatoriaus talpa')),
                ('ram', models.CharField(max_length=255, verbose_name='Operatyvioji atmintis')),
                ('sd', models.BooleanField(default=True, verbose_name='SD kortelės lizdas')),
                ('sd_volume_max', models.CharField(blank=True, max_length=255, null=True, verbose_name='Maksimali SD kortelės talpa')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Kamera (MP)')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Priekinė kamera (MP)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategorija')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=255, verbose_name='Pavardė')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefonas')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Adresas')),
                ('status', models.CharField(choices=[('new', 'Naujas užsakymas'), ('in_progress', 'Užsakymas vykdomas'), ('is_ready', 'Užsakymas paruoštas'), ('completed', 'Užsakymas ivykdytas')], default='new', max_length=100, verbose_name='Užsakymo eiga')),
                ('buying_type', models.CharField(choices=[('self', 'Atvykimas pasiimti'), ('delivery', 'Pristatymas')], default='self', max_length=100, verbose_name='Užsakymo tipas')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Pastabos užsakymui')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Užsakymo sukūrimo data')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Užsakymo gavimo data')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Krepšelis')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='mainapp.customer', verbose_name='Pirkėjas')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Atvaizdas')),
                ('description', models.TextField(null=True, verbose_name='Aprašymas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Kaina')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Įstrižainė')),
                ('display_type', models.CharField(max_length=255, verbose_name='Ekrano tipas')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Procesoriaus dažnis')),
                ('ram', models.CharField(max_length=255, verbose_name='Operatyvioji atmintis')),
                ('video', models.CharField(max_length=255, verbose_name='Vaizdo plokštė')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Akumuliatoriaus darbo laikas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategorija')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='mainapp.Order', verbose_name='Pirkėjo užsakymai'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Bendra kaina')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Krepšelis')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Pirkėjas')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Savininkas'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
    ]
